version: "3.9"
services:
  telegram-video-bot:
    build: .
    container_name: telegram-video-bot
    volumes:
      - ./downloads:/downloads
    ports:
      - "8000:8000"
    restart: unless-stopped
